//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kt4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KT4Entities2 : DbContext
    {
        private static KT4Entities2 _context;
        public KT4Entities2()
            : base("name=KT4Entities2")
        {
        }
        public static KT4Entities2 GetContext()
        {
            if (_context == null)
                _context = new KT4Entities2();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sotdurniki> sotdurniki { get; set; }
    }
}
