//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kt4
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotdurniki
    {
        public int s_id { get; set; }
        public string s_name { get; set; }
        public string s_surname { get; set; }
        public string s_predmet { get; set; }
    }
}
